paths:
  text: "require-text"

shim:
  jquery_ujs:
    deps: ["jquery"]
    exports: "$"
  jquery_tubular:
    deps: ["jquery", "jquery_ui"]
    exports: "$"
  jquery_ui:
    deps: ["jquery"]
    exports: "$"

modules:
  - name: "main"
