# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17bf4ef61c155367c1b9d048e6e1bc87f5919527f1d0785c803c67d5324613bae308170d8bafe7a8c763d13adf369d536a6fd33b0847d37fb25ca5b736c8e893

test:
  secret_key_base: f4b98b9afc1cfdd74d83c5f9029d1eeca29c138e4f49674a4bc8be97dfe8451d5397227e108daed20731c05f1b8840e31d437b6c95ae5b2e6763f4abb5d85a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
